env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript 
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'import'
rules:
  no-var:
    - error
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
  '@typescript-eslint/ban-ts-comment':
    - error
    - 'ts-ignore': 'allow-with-description'
  no-restricted-syntax:
    - error
    - selector: ImportDeclaration[source.value=/\.\./]
      message: Relative parent imports not allowed; please use @orchard root.

settings:
  "import/parsers":
    "@typescript-eslint/parser": [".ts", ".tsx"]
  "import/resolver":
    "typescript":
      "alwaysTryTypes": true
      "project": "."